from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session

from app.core.config import Settings

settings = Settings()

# access the seetings atributes from config.py using the settings object
# and pass them using f-string to the create_engine function to create a connection to the PostgreSQL database.
db_url = f"postgresql+psycopg://{settings.postgres_user}:{settings.postgres_password}@{settings.postgres_host}:{settings.postgres_port}/{settings.postgres_db}"
engine = create_engine(db_url, echo=True)
# echo=True will log all the SQL statements generated by SQLAlchemy to the console for debugging purposes.


def get_session():
    with Session(engine) as session:
        yield session


class Base(DeclarativeBase):
    pass
