from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase
from app.core.config import Settings

settings = Settings()
 
 #access the seetings atributes from config.py using the settings object
 #and pass them using f-string to the create_engine function to create a connection to the PostgreSQL database.
db_url = f"postgresql+psycopg://{settings.postgres_user}:{settings.postgres_password}@localhost:5432/{settings.postgres_db}"
engine = create_engine(db_url, echo=True)
#echo=True will log all the SQL statements generated by SQLAlchemy to the console for debugging purposes.

class Base(DeclarativeBase):
    pass